title: HBC Missions Trip
tagline: HBC Missions Trip
email: your-email@domain.com
description: >
  This is the description thast needs filled in
baseurl: ""
url: ""
theme: bulma-clean-theme

paginate: 5
paginate_path: "/blog/page:num"

plugins:
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

markdown: kramdown
highlighter: rouge

#footer_menu: example_footer_menu
footer_menu: example_footer_menu
