title: HBC Missions Trip
tagline: HBC Missions Trip
email: your-email@domain.com
description: >
  This is the description thast needs filled in
baseurl: ""
url: "https://anelson425.github.io"
remote_theme: chrisrhymes/bulma-clean-theme

paginate: 5
paginate_path: "/blog/page:num"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

#google_analytics: UA-code-here

markdown: kramdown
highlighter: rouge

footer_menu: footer

destination: ./docs
